import type {Metadata} from "next";import Link from "next/link";import {notFound} from "next/navigation";import {Header} from "@/components/Header";import {Footer} from "@/components/Footer";import {Funnel,Arrow} from "@/components/Visuals";import {studies} from "@/lib/data";
export function generateStaticParams(){return studies.map(s=>({slug:s.slug}))}export function generateMetadata({params}:{params:{slug:string}}):Metadata{let s=studies.find(x=>x.slug===params.slug);return s?{title:s.title,description:`${s.title}: ${s.problem} Strategic portfolio case study by Catherine Lazare.`}:{}}
export default function CasePage({params}:{params:{slug:string}}){let idx=studies.findIndex(x=>x.slug===params.slug);if(idx<0)notFound();let s=studies[idx],next=studies[(idx+1)%studies.length];return <><Header/><main><section className="caseHero"><div className="shell"><Link className="back" href="/#work">← All case studies</Link><div className="caseHeroGrid"><div><p className="eyebrow">{s.label}</p><h1>{s.title}</h1><p className="lede">{s.problem}</p><div className="tags">{s.skills.map(x=><span key={x}>{x}</span>)}</div></div><aside><small>STRATEGIC OBJECTIVE</small><p>{s.objective}</p><span>Format</span><b>Independent portfolio case study</b></aside></div></div></section><nav className="caseNav" aria-label="Case study sections"><div className="shell"><a href="#summary">Summary</a><a href="#analysis">Analysis</a><a href="#findings">Findings</a><a href="#recommendations">Recommendations</a><a href="#kpis">KPIs + Impact</a></div></nav>
<section className="caseSection shell" id="summary"><Title n="01" t="Executive summary"/><div className="twoCol"><p className="leadCopy">{s.summary}</p><div><h3>Business challenge</h3><p>{s.challenge}</p><p className="note">This strategic case study presents a decision framework and expected direction of impact. It does not claim measured employer or client results.</p></div></div></section>
<section className="analysis" id="analysis"><div className="shell"><Title n="02" t="Analysis framework"/>{s.slug==="revenue-leak-detection"?<div className="analysisGrid"><div className="whitePanel"><Funnel/></div><div className="diagnostic"><h3>Diagnose each transition</h3>{["Volume: Is enough qualified demand entering?","Conversion: Where does progression weaken?","Velocity: Where do records stall?","Value: Which sources create pipeline quality?"].map((x,i)=><p key={x}><span>0{i+1}</span>{x}</p>)}</div></div>:<div className="systemMap">{["Customer evidence","Process + ownership","Data + technology","Performance + value"].map((x,i)=><div key={x}><small>0{i+1}</small><b>{x}</b><span>→</span></div>)}</div>}<p className="method">The framework is designed to guide analysis once validated organizational data, benchmarks, and stakeholder context are available.</p></div></section>
<section className="caseSection shell" id="findings"><Title n="03" t="Key findings"/><div className="findingGrid">{s.findings.map((f,i)=><article key={f.title}><small>0{i+1}</small><h3>{f.title}</h3><p>{f.text}</p></article>)}</div></section>
<section className="recommend" id="recommendations"><div className="shell"><Title n="04" t="Strategic recommendations"/><div className="recGrid">{s.recommendations.map((r,i)=><article key={r.title}><small>{String(i+1).padStart(2,"0")}</small><h3>{r.title}</h3><p>{r.text}</p></article>)}</div></div></section>
<section className="caseSection shell" id="kpis"><Title n="05" t="KPI framework + expected impact"/><div className="kpiGrid">{s.kpis.map(k=><article key={k.label}><i/><h3>{k.label}</h3><p>{k.why}</p></article>)}</div><div className="impact"><div><p className="kicker">Expected business impact</p><h2>What the recommendations are designed to improve</h2></div><ul>{s.impact.map(x=><li key={x}>{x}</li>)}</ul></div></section><section className="next"><div className="shell"><p>Continue exploring</p><Link href={`/case-studies/${next.slug}`}><span>Next case study</span><b>{next.title}</b><Arrow/></Link></div></section></main><Footer/></>}
function Title({n,t}:{n:string;t:string}){return <div className="numTitle"><span>{n}</span><h2>{t}</h2></div>}

